/**
 * Base HTML template wrapper
 * All pages extend this template
 */

import { escapeHtml } from "../../utils/html"

export interface BaseTemplateOptions {
  title: string
  content: string
  /** Relative path to assets directory (e.g., "../assets" or "../../assets") */
  assetsPath?: string
  /** Additional head content (e.g., meta tags) */
  headExtra?: string
  /** Additional body classes */
  bodyClass?: string
}

/**
 * Render the base HTML page template
 */
export function renderBasePage(options: BaseTemplateOptions): string {
  const {
    title,
    content,
    assetsPath = "./assets",
    headExtra = "",
    bodyClass = "",
  } = options

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="generator" content="opencode-replay">
  <title>${escapeHtml(title)} - OpenCode Replay</title>
  <link rel="stylesheet" href="${assetsPath}/styles.css">
  ${headExtra}
</head>
<body${bodyClass ? ` class="${bodyClass}"` : ""}>
  <div class="container">
    ${content}
  </div>
  <script src="${assetsPath}/search.js"></script>
</body>
</html>`
}

/**
 * Render a simple header with navigation
 */
export function renderHeader(options: {
  title: string
  subtitle?: string
  breadcrumbs?: Array<{ label: string; href?: string }>
  showSearch?: boolean
}): string {
  const { title, subtitle, breadcrumbs = [], showSearch = true } = options

  const breadcrumbHtml =
    breadcrumbs.length > 0
      ? `<nav class="breadcrumbs">
        ${breadcrumbs
          .map((b, i) => {
            const isLast = i === breadcrumbs.length - 1
            if (isLast || !b.href) {
              return `<span class="breadcrumb-item current">${escapeHtml(b.label)}</span>`
            }
            return `<a href="${b.href}" class="breadcrumb-item">${escapeHtml(b.label)}</a>`
          })
          .join('<span class="breadcrumb-separator">/</span>')}
      </nav>`
      : ""

  return `<header class="page-header">
  ${breadcrumbHtml}
  <h1>${escapeHtml(title)}</h1>
  ${subtitle ? `<p class="subtitle">${escapeHtml(subtitle)}</p>` : ""}
  ${
    showSearch
      ? `<div class="search-container">
    <button class="search-trigger" type="button" aria-label="Search">
      <span class="search-icon">&#128269;</span>
      <span class="search-text">Search...</span>
      <kbd>Ctrl+K</kbd>
    </button>
  </div>`
      : ""
  }
</header>`
}

/**
 * Render a simple footer
 */
export function renderFooter(): string {
  return `<footer class="page-footer">
  <p>Generated by <a href="https://github.com/opencode-replay" target="_blank" rel="noopener">opencode-replay</a></p>
</footer>`
}
